##THYMELEAF DEVELOP
spring:
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

server:
  ssl:
    enabled: true
    key-store: keystore.p12
    #    key-store: classpath:keystore.p12(로컬뿐 아닌 개발서버에서도 사용하려면)
    key-store-password: xlwl@1234
    key-store-type: PKCS12
    key-alias: webrct-ssl
  port: 8090

logging:
  level:
    org.springframework: info
    com.huvet.tg: debug
